### ISSUE TITLE
Minimum requirement for Mojolicious is 5.40

### ISSUE THREAD

**Issue by andk** [plicease/Clustericious#11]
As per subject. My smoker just sent a report with 5.39 failing, it looks similar to http://www.cpantesters.org/cpan/report/49307815.

With 5.40 all tests pass. Declared minimum version according to 

https://metacpan.org/source/PLICEASE/Clustericious-0.9940_02/META.yml#L39

is 4.31.

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by plicease** [comment]
This should be fixed in 0.9941
