### ISSUE TITLE
Fails with Mojolicious 6.09 and 6.10

### ISSUE THREAD

**Issue by andk** [plicease/Clustericious#15]
As per subject. At the time of this writing 6.10 is current.

Sample fail report:

http://www.cpantesters.org/cpan/report/54606602

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by plicease** [comment]
confirmed, I am able to reproduce with mojo 6.10 and master

**Comment by plicease** [comment]
Fixed in 0.9946
